apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.Name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: {{ .Release.Name }}-sc
