apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-sc
  namespace: {{ .Values.namespace }}
provisioner: {{ .Values.storageClass.provisioner }}
volumeBindingMode: {{ .Values.storageClass.volBind }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
parameters:
  type: {{ .Values.storageClass.type }}
