apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
stringData:
  MONGODB_URI: {{ .Values.secret.URI }}
  SESSION_SECRET: {{ .Values.secret.session }}
  EMAIL_USER: {{ .Values.secret.email }}
  EMAIL_PASS: {{ .Values.secret.pass }}
